### PR TITLE
Adjacency rcpp code

### PR DESCRIPTION
**Pull request by Nowosad**
There is also a few helper functions that potentially could be helpful...

https://github.com/marcosci/landscapemetrics/issues/19

### CODE REVIEW

**Comment by marcosci** [comment]
Merged it, really neat stuff Jakub :-) If you something I miss to replace in the next days or have an idea to replace something we did - just drop me a message :v:

**Comment by Nowosad** [comment]
Sure thing @marcosci. I am really happy that is useful.

**Comment by Nowosad** [comment]
BTW @marcosci and @mhesselbarth - I am quite bad in c++, but I enjoy it a little bit. Let me know if there are any pieces of code that are still slow and their rcpp counterparts are needed.

**Comment by mhesselbarth** [comment]
It would be really helpful if one can specify the neighborhood of your adjacency function using e.g. a matrix  and not being "limited" to the queen's or rook's case (comparable to the raster::adjacency directions option).

**Comment by Nowosad** [comment]
:+1: 
I've opened a new issue and will work on it in the next few days.
https://github.com/marcosci/landscapemetrics/issues/21

**Pull request merged**
